server:
  port: 8081

spring:
  r2dbc:
    url: ${SPRING_R2BC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
  output:
    ansi:
      enabled: ALWAYS
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  flyway:
    locations: "classpath:db/postgres/migration"
    url: ${SPRING_J2BC_URL}
  security:
    webflux:
      formLogin:
        enabled: false

logging:
  level:
    web: DEBUG
    org:
      springframework:
        security: DEBUG
        boot:
          autoconfigure:
            flyway: DEBUG
        web:
          reactive:
            result:
              method:
                annotation: DEBUG
        validation: DEBUG
        jdbc:
          datasource: DEBUG
      flywaydb: DEBUG
    jakarta:
      validation=DEBUG: