server:
  port: 8081

spring:
  r2dbc:
    url: ${SPRING_R2BC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
  output:
    ansi:
      enabled: ALWAYS
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  security:
    webflux:
      formLogin:
        enabled: false

logging:
  level:
    org:
      springframework:
        security: DEBUG